apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        image: registryldb3678.azurecr.io/poi:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: sqlserver
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: ASPNETCORE_ENVIRONMENT
            value: Development