apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  labels:
    app: userprofile 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile 
  template:
    metadata:
      labels:
        app: userprofile 
    spec:
      containers:
      - name: userprofile 
        image: registryldb3678.azurecr.io/userprofile:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: sqlserver
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username