apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryldb3678.azurecr.io/trips:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-from-kv
                key: password
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: secrets-from-kv
                key: sqlserver
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: secrets-from-kv
                key: username
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"